# This is a basic workflow to help you get started with Actions

name: Tennis Build and Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: Tennis
  pull_request:
    branches: [ main ]
    paths: Tennis
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2      

      - name: Restore NuGet Packages
        run: nuget restore Tennis\Tennis.sln
        
      - name: Build and Publish Web App
        run: msbuild Tennis\Tennis.sln /p:Configuration=Release
        
      - name: Setup VSTest and add to PATH
        uses: darenm/Setup-VSTest@v1
      
      - name: Run VSTest
        id: run_vstest
        run: vstest.console.exe .\CalcStatistics\CalcStats\CalcStatsTests\bin\Debug\CalcStatsTests.dll /Platform:x64        
